name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: golang:1.15.6-alpine3.12

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t hello . && docker run --rm -it hello
