name: Simple Job
on:
  push:
    branches:
    - main

jobs:

  Hello:
    runs-on: windows-latest
    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        vs-version: '[16.4,16.5)'
    - name: Docker build
      run: docker build -t hello -f ../../Dockerfile .
    - name: Dokcer run 
      run: docker run --rm  -it hello
