name: Simple Job
on:
  push:
    branches:
    - main

jobs:

  Hello:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - shell: cmd
    - name: Docker build
      run: docker build -t hello -f ../../Dockerfile .
    - name: Dokcer run 
      run: docker run --rm  -it hello
