name: Simple Job
on:
  push:
    branches:
    - main

jobs:

  Hello:
    runs-on: windows-latest
    steps:
    - name: Display the path
      run:  echo %PATH%
      shell: cmd
    - name: Docker build
      run: docker build -t hello -f ../../Dockerfile .
    - name: Dokcer run 
      run: docker run --rm  -it hello
