name: Simple Job
on:
  push:
    branches:
    - main

jobs:

  Hello:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Docker build
      run: docker build -t hello -f ../../Dockerfile .
    - name: Dokcer run 
      run: docker run --rm  -it hello
